# Generated by Django 4.1.1 on 2023-12-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=4)),
                ('saude', models.TextField(max_length=1000)),
                ('historia', models.TextField(max_length=1500)),
                ('especie', models.TextField(max_length=50)),
                ('foto', models.TextField(max_length=200)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doador.doador')),
            ],
            options={
                'db_table': 'Pet',
            },
        ),
    ]
