# Generated by Django 4.1.1 on 2023-12-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adotante', '0001_initial'),
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('data_atualizacao', models.DateField(auto_now_add=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adotante.adotante')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doador.doador')),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
    ]
