# Generated by Django 4.1.1 on 2023-12-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id_localizacao', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.DecimalField(decimal_places=0, max_digits=10)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doador.doador')),
            ],
            options={
                'db_table': 'Localizacao',
            },
        ),
    ]
