# Generated by Django 4.1.1 on 2023-12-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='senha',
            new_name='password',
        ),
        migrations.AddField(
            model_name='doador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
