# Generated by Django 4.1.1 on 2023-12-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adotante',
            old_name='senha',
            new_name='password',
        ),
        migrations.AddField(
            model_name='adotante',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='nome',
            field=models.EmailField(max_length=100),
        ),
    ]
